### ISSUE TITLE
Cenário Atual do Cliente e do Negócio

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2024.2-T01-CD-MOJ#3]
- [ ]  - O problema está muito amplo: "insatisfação do usuário". Precisa ser revisto.
- [ ]  - O diagrama de Ishikawa não está muito visível, precisa ser melhorado.
- [ ]  - perfil "Instituições educacionais e departamentos acadêmicos: " é preciso dizer o perfil das pessoas.

**Comment by iagorrr** [comment]
Acredito que fiz as alterações necessárias, @phmelosilva poderia verificar por favor ?

**Comment by phmelosilva** [comment]
@iagorrr  deixar aqui uma lista de acordo com as modificações que o professor pediu:
- [ ] O problema principal que o professor se referiu é a cabeça do peixe, apontado no Ishikawa: "Insatisfação dos 
usuários  com a plataforma em relação a carência de funcionalidades". Isso poderia ser mudado para algo como "ausência de funcionalidades fundamentais e limitações na experiência de uso", ou algo nesse sentido, que deixa "Insatisfação dos Usuários", menos amplo e que também acaba entrando nesse mesmo escopo da insatisfação. Então precisa estar explícito que o problema é que muitos usuários não possuem interesse de uso elevado na plataforma por conta das limitações apresentadas pelos problemas e falta de funcionalidades, o que causa a insatisfação desses usuários. Ou seja, se atentem quanto a como descrever o problema. 

- [X] Ishikawa, melhorou a visibilidade.

 - [ ] Sobre os perfis presentes em segmentação de clientes, as modificações em cima de Instituições educacionais e departamentos acadêmicos estão mais coerentes, mas está um pouco destoante quanto a organização de como os outros 2 perfis estão apresentados, não acha? Para melhorar a organização do texto, seria melhor trazer essa mesma organização feita em Professores(as) de instituições acadêmicas, para Estudantes de programação e computação. Uma sugestão é tentar trazer nessa seção, mais claramente como cada perfil se relaciona com o outro e com o problema em questão, além de trazer as expectativas quanto ao que se espera ter na solução, caso consigam isso com os clientes.

**Comment by iagorrr** [comment]
@phmelosilva obrigado pelo feedback !
Fiz as alterações que você sugeriu, tomei também a liberdade de remover a segmentação de clientes "Professores, tutores e organizadores de competições", pois achei que estava redundante com a de "Professores(as) de instituições acadêmicas"

Agora está assim:
![image](https://github.com/user-attachments/assets/7f503130-9cdd-4f12-bd9a-e4cb76888bf2)
