### ISSUE TITLE
Solução Proposta

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2024.2-T01-CD-MOJ#4]
Estabelecer um único objetivo principal relacionado diretamente ao problema, e colocar objetivos secundários.

**Comment by andreozzi** [comment]
Acho que ja fiz as alterações necessarias, @phmelosilva poderia verificar para mim porfavor ?

**Comment by phmelosilva** [comment]
@andreozzi ficou bem legal os objetivos definidos, destrincharam bem cada um deles. 

Conseguem relacionar os objetivos propostos com o Cenário atual do Cliente e do Negócio? O que quero dizer é que ter um texto introdutório conectando a solução proposta com o cenário do cliente e do negócio ajuda a compreender o porquê a escolha do objetivo principal de vocês foi definida. Com isso feito, o artefato ficara bem mais coeso com os outros artefatos produzidos.

Um detalhe que vi foi aqui no markdown, onde há um pequeno erro no tópico 3 com um S a mais para ser corrigido. Veja na imagem:
![image](https://github.com/user-attachments/assets/351e2444-9950-49e4-a3a9-99a8bc3b9a93)

**Comment by andreozzi** [comment]
@phmelosilva Muito Obrigado pelo feedback! Acabei de terminar de realizar as alterações que indicou acredito que eu ja tenha finalizado.
