### ISSUE TITLE
Estratégias de Engenharia de Software

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2024.2-T01-CD-MOJ#5]
Estratégia priorizada
Abordagem de Desenvolvimento de Software: Dirigida a Plano
Ciclo de vida: Iterativo de incremental
Processo de Engenharia de Software: Híbrido

- [x] A equipe não informou de que maneira, prática, será feita a utilização dos processos informados.
- [x] A equipe diz que a abordagem é Dirigida a Plano, mas apresenta processos ágeis (RAD e OpenUp). Incorreto.

**Comment by phmelosilva** [comment]
@fxred falta detalhamento de como vão aplicar as Etapas específicas do OpenUP, o processo ainda não está claro de como será aplicado no projeto. Vocês explicaram bastante o "porque" vão aplicar, mas não demonstraram na prática como isso vai ser feito. Por exemplo, em que etapas do projeto vocês vão encaixar o Inception, Elaboration, Construction e Transition?

E que elementos do RAD vão utilizar? A frase usada: " RAD híbrido para contribuir na rapidez do processo de desenvolvimento." não está muito claro em que tipo de aplicação o RAD é usado. Como que ele contribuí para essa rapidez? 

Do jeito explicado, o próprio OpenUP já contribuí no processo ágil e rápido de desenvolvimento, então o que será incluído do RAD e como isso se aplica no projeto?

**Comment by fxred** [comment]
@phmelosilva dei uma detalhada no documento e exemplifiquei como na prática vão ser usadas as fases do OpenUP e o RAD também. E sobre a última pergunta, ficou mais claro agora lá no documento, mas decidimos incluir o RAD no processo pelas características de feedback rápido do cliente e prototipação

**Comment by phmelosilva** [comment]
Beleza, ficou mais detalhado.
