### ISSUE TITLE
Cronograma e Entregas

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2024.2-T01-CD-MOJ#6]
Cronograma está bem resumido, deve utilizar o padrão do template.

**Comment by CaioHabibe** [comment]
@phmelosilva opa Pedro, acredito que resolvemos essa issue de acordo com o ultimo commit feito no repositório: https://github.com/mdsreq-fga-unb/2024.2-T01-CD-MOJ/commit/33ca7c51660d8fa304d6c02f4c46cf46b078a4ed

**Comment by phmelosilva** [comment]
@CaioHabibe Commit validado !
