### ISSUE TITLE
Interação Entre Equipe e Cliente

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2024.2-T01-CD-MOJ#7]
- [ ] Não apresenta papeis e responsabilidades de REQ
- [ ] Não estão claros os processos de comunicação entre equipe e com o cliente, falam apenas das ferramentas

**Comment by PedroHhenriq** [comment]
Opa, @phmelosilva Acredito ter feito as alterações na issue. Poderia dar uma olhadinha e verificar se está adequado?

**Comment by phmelosilva** [comment]
@PedroHhenriq está bem melhor! Podem marcar como concluído, vou fechar a issue para vocês.

**Comment by phmelosilva** [comment]
@PedroHhenriq está bem melhor! Podem marcar como concluído, vou fechar a issue para vocês.
